//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Association
    {
        public int AssociationId { get; set; }
        public string Name { get; set; }
        public string SmallImage { get; set; }
        public string LargeImage { get; set; }
        public int StartYear { get; set; }
        public string Mission { get; set; }
    }
}
