//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        public int BoardId { get; set; }
        public string Title { get; set; }
        public string Member { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    }
}
