//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GAEntities : DbContext
    {
        public GAEntities()
            : base("name=GAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventDocuments> EventDocuments { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Links> Links { get; set; }
        public virtual DbSet<Rules> Rules { get; set; }
        public virtual DbSet<FAQ> FAQ { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<MemberWinnings> MemberWinnings { get; set; }
        public virtual DbSet<WinningTypes> WinningTypes { get; set; }
        public virtual DbSet<Association> Association { get; set; }
        public virtual DbSet<Board> Board { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
    }
}
